
-- 11/11/2019 notes

SELECT *
FROM member;
-- create table accnt
CREATE TABLE account (
acc_num         VARCHAR(7) PRIMARY KEY      ,
acc_opendate    DATE DEFAULT SYSDATE        ,
acc_balance     NUMBER(10,2)                 ,
acc_limit       NUMBER (10,2) DEFAULT 5000 NOT NULL ,
mem_num         NUMBER   NOT null                           ,
CONSTRAINT account_mem_num_fk foreign KEY(mem_num)    references member
);


-- alter table  gives ability to change structure of table
-- 3 diff types add, modify, and drop


-- MODIFY
ALTER TABLE ACCOUNT
MODIFY ACC_BALANCE DEFAULT 0 NOT NULL;


-- ADD
ALTER TABLE ACCOUNT
ADD CONSTRAINT ACCOUNT_BAL_LIMIT_CK CHECK (ACC_BALANCE <= ACC_LIMIT);


 -- ADDED NEW COLUMN TO TABLE
ALTER TABLE ACCOUNT
ADD ACC_CLOSEDATE DATE DEFAULT SYSDATE;


SELECT *
FROM ACCOUNT;


-- INSERT DATA INTO ACCOUNT TABLE
INSERT INTO ACCOUNT VALUES ('1234567','15-OCT-19',0,4000,101,NULL);
INSERT INTO ACCOUNT VALUES ('2345678', DEFAULT, 0, 5000, 102, NULL);

INSERT INTO ACCOUNT (ACC_NUM, MEM_NUM) VALUES ('3456789',101);

-- COMMIT OR FINALIZE TABLE CHANGES
COMMIT;


-- CHANGE A ROW WITH UPDATE
UPDATE ACCOUNT
SET ACC_BALANCE = 100
WHERE ACC_NUM = '1234567';



UPDATE ACCOUNT
SET ACC_BALANCE = ACC_BALANCE + 500,
    ACC_LIMIT = 6000
WHERE ACC_NUM = '1234567';



UPDATE ACCOUNT
SET ACC_LIMIT = ACC_LIMIT + 1000
WHERE MEM_NUM = 101;



-- DELETE ROW

DELETE FROM ACCOUNT
WHERE ACC_NUM = '2345678';


-- ROLLBACK    IS THE COUNTERPART TO COMMIT WILL UNDO ALL CHANGES TO LAST BEFORE TIME BEFORE COMMIT

ROLLBACK;


-- VIEWS
CREATE VIEW PRODAVERAGES AS
SELECT P_CODE, P_DESCRIPT, P_PRICE, AVGPRICE, P_PRICE - AVGPRICE AS DIFF, PRODUCT.V_CODE, V_NAME
FROM PRODUCT  LEFT JOIN (SELECT VENDOR.V_CODE,  V_NAME, Avg(P_PRICE) AS AVGPRICE
                        FROM VENDOR  LEFT JOIN PRODUCT ON VENDOR.V_CODE = PRODUCT.V_CODE
                        GROUP BY VENDOR.V_CODE, V_NAME)VENDAVGS ON PRODUCT.V_CODE = VENDAVGS.V_CODE
ORDER BY PRODUCT.V_CODE, P_CODE;


SELECT P_CODE, P_DESCRIPT, V_NAME, DIFF
FROM PRODAVERAGES
WHERE DIFF > 0;

-- USE VIEWS TO IMPROVE SECURITY , HIDE COMPLEXITY OF UNDERLYING QUERY


SELECT * FROM USER_VIEWS;


SELECT * FROM ALL_VIEWS WHERE VIEW_NAME = 'USER_TABLES';



-- TO REMOVE VIEW
DROP VIEW PRODAVERAGES;

-- CANT USE VIEWS FOR ANY ASSIGNMENTS IN THIS COURSE UNLESS EXPLICITLY STATED