CREATE TABLE SCHEDULE AS SELECT * FROM MAG.SCHEDULE;
CREATE TABLE PART AS SELECT * FROM MAG.PART;
CREATE TABLE WORKER AS SELECT * FROM MAG.WORKER;
CREATE TABLE JOB AS SELECT * FROM MAG.JOB;
CREATE TABLE EQUIPMENT AS SELECT * FROM MAG.EQUIPMENT;







-- 1 WORKS
SELECT (WORKER.WORK_FNAME || ' ' || WORK_LNAME) AS WORKER, PART.PART_DESCRIPT, TO_CHAR (Round(AVG((WORKER.WORK_WAGE * JOB.JOB_HOURS_WORKED) / JOB_QTY_PRODUCED),2),'$0.99') AS " Avg Labor Cost per Unit", Count(JOB_QTY_PRODUCED) AS " Times Produced"
FROM   WORKER JOIN JOB ON WORKER.WORK_NUM = JOB.WORK_NUM
        JOIN PART ON JOB.PART_NUM = PART.PART_NUM
HAVING   Count(JOB_QTY_PRODUCED) > 2
GROUP BY WORKER.WORK_FNAME, WORKER.WORK_LNAME , PART.PART_DESCRIPT
ORDER BY AVG((WORKER.WORK_WAGE * JOB.JOB_HOURS_WORKED) / JOB_QTY_PRODUCED) ASC;


-- 2
SELECT PART.PART_NUM, PART_DESCRIPT, PART_QOH, SCHEDULE.SCH_PLAN_QTY
FROM  PART JOIN SCHEDULE ON PART.PART_NUM = SCHEDULE.PART_NUM
WHERE





